name: trabalheja
description: "A new Flutter project."
publish_to: 'none'



environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400 # Regular
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500 # Medium
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700 # Bold

