name: trabalheja
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2



environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  supabase_flutter: ^2.10.3
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.2.0
  dotted_border: ^3.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  http: ^1.2.0
  pointycastle: ^3.8.0
  basic_utils: ^5.5.0
  encrypt: ^5.0.1
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400 # Regular
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500 # Medium
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700 # Bold

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ios (1).png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF" # fundo branco para Android adaptive icon
  adaptive_icon_foreground: "assets/icons/ios (1).png"

